title: Learning.Rocks
description: >
  Conheça melhor o time de engenharia da plataforma LXM do Learning Rocks,
  seus desafios técnicos e aprendizados.
github_username: skore-io
linkedin_username: ciatech-uoledtech
show_excerpts: true

plugins:
  - jekyll-feed
  - github-pages

repository: skore-io/culture
baseurl: '/culture'
