services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
    environment:
      - PAGES_REPO_NWO=skore-io/culture
      - JEKYLL_ENV=production
      - JEKYLL_FORCE_POLLING=true
    command: bundle exec jekyll serve --host 0.0.0.0 --watch
